# Generated by Django 4.2 on 2023-05-16 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliNombre', models.CharField(db_comment='Nombre del cliente', max_length=45)),
                ('cliApellido', models.CharField(db_comment='Apellido del cliente', max_length=45)),
                ('cliTelefono', models.CharField(db_comment='Telefono del cliente', max_length=45)),
                ('cliCorreo', models.CharField(db_comment='Correo electronico del cliente', max_length=45)),
                ('cliDireccion', models.CharField(db_comment='Direccion fisica del cliente', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libNombre', models.CharField(db_comment='Título del libro es el nombre principal que lo identifica', max_length=45)),
                ('libAutor', models.CharField(db_comment='Autor del libro', max_length=45)),
                ('libISBN', models.CharField(db_comment='Código único asignado a cada libro', max_length=50, unique=True)),
                ('libGenero', models.CharField(choices=[('Novela', 'Novela'), ('Ciencia ficcion', 'Ciencia ficcion'), ('Romance', 'Romance'), ('Historia', 'Historia')], db_comment='Genero del libro', max_length=50)),
                ('libAñoPublicacion', models.IntegerField(db_comment='Año de publicacion del libro', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preCodigo', models.CharField(db_comment='Codigo unico de prestamo', max_length=45, unique=True)),
                ('preFechaPrestamo', models.DateField(db_comment='Corresponde a la fecha que el libro es retirado')),
                ('preFechaEntrega', models.DateField(db_comment='Corresponde a la fecha que el libro es regresado ')),
                ('preEstado', models.CharField(choices=[('En prestamo', 'En prestamo'), ('Devuelto', 'Devuelto')], db_comment='Estado del prestamo', default='En prestamo', max_length=40)),
                ('preCliente', models.ForeignKey(db_comment='Hace relación al elemento FK', on_delete=django.db.models.deletion.PROTECT, to='appGestionLibros.cliente')),
                ('preLibro', models.ForeignKey(db_comment='Hace relación al elemento FK', on_delete=django.db.models.deletion.PROTECT, to='appGestionLibros.libro')),
            ],
        ),
    ]
