# Generated by Django 4.2 on 2023-05-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionLibros', '0002_rename_libañopublicacion_libro_libanopublicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='preEstado',
            field=models.CharField(choices=[('En prestamo', 'En prestamo'), ('Devuelto', 'Devuelto')], db_comment='Estado del prestamo', default='En prestamo', max_length=40, null=True),
        ),
    ]
